### ISSUE TITLE
Upload to pypi?

### ISSUE THREAD

**Issue by gvauter** [iromli/flask-flywheel#3]
Any chance you plan on uploading this to pypi for easy pip install?

**Comment by iromli** [comment]
I'm a little bit busy with work these days. I'll try uploading it on this weekend.
Thanks.

**Comment by gvauter** [comment]
Ok thanks, much appreciated!

**Comment by iromli** [comment]
@gvauter sorry for late response ... I have uploaded the package to PyPI. Please try `pip install flask-flywheel`.

**Comment by gvauter** [comment]
Ok great, Thank you!
